language: ruby
rvm:
- 2.0.0
- 2.1.0
- jruby
before_install:
- sudo apt-get install flac
- rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  slack:
    secure: FpXxivsKJnyU9lmv6yTUFDGp+D74AFFGHTcWJnmS5U3uMZEAbXCjNTKlCF73c+FpfKS9LQu+6O3KylRwG6oLTkuTb0OzNVTKXxQV2YdFqBxvWs5oAN4FqhDFj6FcDt7NNAlBHV8fDY/9PY4UMCWuZmprrADVl6fy+R1Z2Z6y3pk=
env:
  global:
    secure: E+fPXR+FH9gthRwawDC7DbU2gv1F8YaNypHHe4KRx+cvyNfZIyArGS5u6l28cqxZG2dOyPUu4LU6S69ylhfrc3VkwOcc4ZQIpaxbXv3DAjwdXWwVN1Dt7W1cDA011oYbPPJe2N0gZeFVqPx2cSzXcW4nKN8A7ZR3LZ5l+ojIwqA=
