# frozen_string_literal: true

require "flacsmith/identity"
require "flacsmith/errors/base"
require "flacsmith/errors/invalid_metadata_key"
require "flacsmith/errors/track"
require "flacsmith/metadata/formatter"
require "flacsmith/metadata/tag"
require "flacsmith/metadata/file"
require "flacsmith/metadata/picture"
require "flacsmith/metadata/tagger"
require "flacsmith/metadata/builder"
require "flacsmith/converters/track"
require "flacsmith/converters/album"
require "flacsmith/cli"
